### ISSUE TITLE
Can this project work without UTA dataset only with csv files?

### ISSUE THREAD

**Issue by leijobs** [hackenjoe/drowsiness_detection#1]
Hello, thanks for your sharing and I wonder if it works without the UTA datasets only use the csv files? Since the dataset is too large. And if I want to test my video of drowiness driver should I extract drowiness features (kit provided in the repo) then put it in this work so I can get the results?

**Comment by hackenjoe** [comment]
Yes you can test the script without the video files. The KNN classifier works with the provided csv files. Just the CNN network requires images from the videos. You can also use your own video analogous to the videos from UTA. You may have to adjust the start time (depending on the length of your video) in `getFrame()` method.
