### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by TushtiSachdeva** [hackenjoe/drowsiness_detection#4]
Hey. I am also working on driver drowsiness detection. 
I am wondering how did you get the CSV files as I couldn't find them in the dataset folders. Did you create them on your own?
Could you also explain what are the values you stored in each column and how to use it?

**Comment by hackenjoe** [comment]
Hey,
yes the csv files containing numerical variables calculated mainly on the basis of the UTA videos. The meaning of the features and their values can be read in drowsiness_detection.ipynb (see section 2.2 extract features).
